export const knowledgeBase = [
  {
    id: 'food-survival-ordering',
    module: 'food',
    title: 'Survival Chinese for ordering food',
    aliases: ['order food', 'night market', 'restaurant', 'stinky tofu', '便當', '夜市', '點餐'],
    keywords: ['order', 'food', 'restaurant', 'night', 'market', 'stinky', 'tofu', 'spicy', 'takeout', 'dine', '點餐', '臭豆腐', '外帶', '內用', '辣'],
    shortAnswer: 'For simple ordering, point at the menu and combine “我要” with the item, quantity, and any preference such as no spicy or takeout.',
    chinese: '我要一份臭豆腐，不要辣，外帶，謝謝。',
    pinyin: 'wǒ yào yí fèn chòu dòufu, bú yào là, wài dài, xièxie.',
    english: 'I would like one serving of stinky tofu, not spicy, to go. Thank you.',
    whenToUse: 'Use this at night markets, small eateries, or food stalls when ordering one portion and requesting takeout.',
    culturalNote: 'Taiwanese small eateries often expect direct, concise ordering. “一份” works well for many snacks, and “不要辣” is commonly understood.',
    source: 'Curated Taiwanese ordering phrase set',
    lastUpdated: '2026-05-31',
    credibility: 'curated'
  },
  {
    id: 'food-bubble-tea',
    module: 'food',
    title: 'Bubble tea sweetness and ice',
    aliases: ['bubble tea', 'boba', 'drink shop', 'milk tea', '手搖飲', '珍珠奶茶'],
    keywords: ['bubble', 'tea', 'boba', 'drink', 'sweetness', 'ice', 'sugar', 'milk', '半糖', '微冰', '珍珠', '奶茶'],
    shortAnswer: 'At drink shops, be ready to choose sweetness and ice level after saying the drink name.',
    chinese: '我要一杯珍珠奶茶，半糖微冰。',
    pinyin: 'wǒ yào yì bēi zhēnzhū nǎichá, bàn táng wēi bīng.',
    english: 'I would like one bubble milk tea, half sugar and less ice.',
    whenToUse: 'Use this at hand-shaken drink shops when ordering a drink with customized sweetness and ice.',
    culturalNote: 'Common options include 無糖, 微糖, 半糖, 少冰, 微冰, and 去冰. If unsure, “半糖微冰” is a common moderate choice.',
    source: 'Curated Taiwanese drink shop phrase set',
    lastUpdated: '2026-05-31',
    credibility: 'curated'
  },
  {
    id: 'campus-insurance',
    module: 'campus',
    title: 'NTHU insurance overview for international students',
    aliases: ['health insurance', 'NHI', 'ARC', 'student insurance', 'group insurance', '健保', '保險'],
    keywords: ['insurance', 'health', 'nhi', 'arc', 'doctor', 'medical', 'student', 'group', '健保', '保險', '居留證'],
    shortAnswer: 'NTHU describes three insurance types that may affect international students: international group insurance for the first semester, National Health Insurance after ARC-related eligibility, and student insurance for registered NTHU students.',
    chinese: '我想確認我的保險狀態，請問我現在有團體保險、學生保險，還是健保？',
    pinyin: 'wǒ xiǎng quèrèn wǒ de bǎoxiǎn zhuàngtài, qǐngwèn wǒ xiànzài yǒu tuántǐ bǎoxiǎn, xuéshēng bǎoxiǎn, háishì jiànbǎo?',
    english: 'I would like to confirm my insurance status. Do I currently have group insurance, student insurance, or National Health Insurance?',
    whenToUse: 'Use this when contacting NTHU staff or asking a buddy to help you check which coverage applies to you now.',
    culturalNote: 'Insurance depends on registration, ARC status, timing, and fees. Do not rely on memory for personal eligibility; confirm with the responsible NTHU office.',
    source: 'NTHU Student Insurance page: https://apply.nthu.edu.tw/en/article/148-insurance',
    lastUpdated: '2025-05-08',
    credibility: 'official'
  },
  {
    id: 'campus-scholarship',
    module: 'campus',
    title: 'NTHU international student scholarships',
    aliases: ['scholarship', 'tuition waiver', 'funding', '獎學金'],
    keywords: ['scholarship', 'tuition', 'waiver', 'funding', 'application', 'undergraduate', 'master', 'phd', '獎學金', '學雜費'],
    shortAnswer: 'NTHU says international students may apply for NTHU International Student Scholarships during the application process, and scholarship review considers application materials and interviews. Undergraduate awards must be renewed each academic year.',
    chinese: '請問國際學生獎學金的申請資格、期限和需要文件是什麼？',
    pinyin: 'qǐngwèn guójì xuéshēng jiǎngxuéjīn de shēnqǐng zīgé, qíxiàn hé xūyào wénjiàn shì shénme?',
    english: 'What are the eligibility requirements, deadline, and required documents for the international student scholarship?',
    whenToUse: 'Use this when emailing or visiting the NTHU office responsible for international student scholarship questions.',
    culturalNote: 'Scholarship rules and deadlines change by year and degree level, so always check the official application system or OGA page before making decisions.',
    source: 'NTHU scholarship FAQ: https://ibp.nthu.edu.tw/faq-9.html; Scholarships listing: https://apply.nthu.edu.tw/en/articles/nthu-scholarships?type=scholarship',
    lastUpdated: '2026-05-31',
    credibility: 'official'
  },
  {
    id: 'campus-office-contact',
    module: 'campus',
    title: 'Finding the right campus office',
    aliases: ['office', 'OGA', 'contact', 'global affairs', 'international office', '國際處'],
    keywords: ['office', 'contact', 'oga', 'global', 'affairs', 'arc', 'housing', 'insurance', 'email', '國際處', '聯絡'],
    shortAnswer: 'For work permit, ARC, housing, and insurance questions, NTHU contact information points students to the Division of Global Students Recruitment and Service.',
    chinese: '請問我應該聯絡哪個單位處理 ARC、住宿或保險問題？',
    pinyin: 'qǐngwèn wǒ yīnggāi liánluò nǎge dānwèi chǔlǐ ARC, zhùsù huò bǎoxiǎn wèntí?',
    english: 'Which office should I contact for ARC, housing, or insurance questions?',
    whenToUse: 'Use this when you are unsure which NTHU office handles your international student administrative question.',
    culturalNote: 'Administrative offices in Taiwan may divide responsibilities by topic. A clear one-sentence question helps staff redirect you faster if needed.',
    source: 'NTHU contact page: https://apply.nthu.edu.tw/en/article/99-information',
    lastUpdated: '2026-05-31',
    credibility: 'official'
  },
  {
    id: 'social-first-chat',
    module: 'social',
    title: 'Low-pressure first conversations',
    aliases: ['make friends', 'classmates', 'conversation', 'chat', '交朋友', '聊天'],
    keywords: ['friend', 'classmate', 'talk', 'conversation', 'chat', 'social', 'food', 'course', 'club', '交友', '聊天', '同學'],
    shortAnswer: 'Start with low-pressure topics such as food, courses, campus life, clubs, and activities near NTHU.',
    chinese: '你有推薦清大附近的餐廳嗎？',
    pinyin: 'nǐ yǒu tuījiàn Qīngdà fùjìn de cāntīng ma?',
    english: 'Do you recommend any restaurants near NTHU?',
    whenToUse: 'Use this with classmates, buddies, or club members when you want a natural opening topic.',
    culturalNote: 'For first conversations, avoid jumping into very private topics such as salary, politics, or relationship status unless the other person brings them up.',
    source: 'Curated Taiwanese campus social etiquette set',
    lastUpdated: '2026-05-31',
    credibility: 'curated'
  },
  {
    id: 'social-activity-invite',
    module: 'social',
    title: 'Asking about activities',
    aliases: ['activity', 'club', 'event', 'invite', '活動', '社團'],
    keywords: ['activity', 'event', 'club', 'invite', 'go', 'join', '活動', '社團', '一起'],
    shortAnswer: 'Campus events and clubs are good ways to talk with Taiwanese classmates because the shared activity gives everyone context.',
    chinese: '這個活動你會去嗎？如果你去，我可以一起去嗎？',
    pinyin: 'zhège huódòng nǐ huì qù ma? rúguǒ nǐ qù, wǒ kěyǐ yìqǐ qù ma?',
    english: 'Are you going to this event? If you are, may I go together with you?',
    whenToUse: 'Use this when discussing a campus activity, club event, or international student gathering.',
    culturalNote: 'Taiwanese invitations can be indirect. If someone says “下次一起,” follow up with a specific time or event to see whether it is a real plan.',
    source: 'Curated Taiwanese campus social etiquette set',
    lastUpdated: '2026-05-31',
    credibility: 'curated'
  }
];

export const moduleLabels = {
  food: '食 Food',
  campus: '校園 Campus',
  social: '交友 Social'
};
